apiVersion: apps/v1
kind: Deployment
metadata:
  name: bipolar-frontend
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bipolar-frontend
  template:
    metadata:
      labels:
        app: bipolar-frontend
    spec:
      containers:
        - name: web
          image: 983774590472.dkr.ecr.us-east-1.amazonaws.com/bipolar-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
