name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FE_BUCKET: terraform-20250907201205156800000001
      CF_DIST_ID: E1NXDXKR1Q01XI
      REACT_APP_API_BASE_URL: http://bipolar-alb-700384359.us-east-1.elb.amazonaws.com
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::983774590472:role/github-ecr
          aws-region: us-east-1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install & build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Determine build path
        id: path
        run: |
          for d in build dist out; do
            if [ -d "frontend/$d" ]; then
              echo "dir=frontend/$d" >> "$GITHUB_OUTPUT"; exit 0
            fi
          done
          echo "No build dir found"; exit 1
      
      - name: Sync to S3
        run: aws s3 sync "${{ steps.path.outputs.dir }}" "s3://${FE_BUCKET}" --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id "$CF_DIST_ID" --paths "/*"
